name: Gradle Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate Gradle wrapper
        run: gradle wrapper

      - name: Execute Gradle build
        run: ./gradlew clean build
